- name: Disabling 000-default.conf
  command: sudo a2dissite 000-default.conf
  when: ansible_distribution == "Ubuntu"

- name: Copying the apache config.
  template:
    src: "elis.tech.conf.j2"
    dest: '{{"/etc/apache2/sites-available/{{domain_name}}.conf" if ansible_distribution == "Ubuntu" else "/etc/httpd/conf/httpd.conf"}}'
  notify: Restart apache

- name: Enabling the new apache config.
  command: "sudo a2ensite {{domain_name}}.conf"
  notify: Restart apache
  when: ansible_distribution == "Ubuntu"

- name: Enable url rewriting
  command: "sudo a2enmod rewrite"
  notify: Restart apache
  when: ansible_distribution == "Ubuntu"