---
# tasks file for lamp_stack
  - name: Set Server Host Name.
    hostname:
      name: '{{ host_name }}'

  - name: Print the OS type.
    debug:
      msg: "{{ ansible_distribution }}"

  - name: Updating Ubuntu Server Distros 'apt update && apt upgrade.'
    apt:
      upgrade: safe
      update_cache: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Updating the CentOS server 'yum update and upgrade.'
    yum:
      update_cache: yes
      skip_broken: yes
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

  - name: Install needed packages(Debian).
    apt:
      name: '{{ item }}'
      state: latest
    with_items: '{{debian_packages}}'
    when: ansible_distribution == "Ubuntu"

  - name: Install needed packages(CentOS).
    yum:
      name: '{{ item }}'
      state: latest
    with_items: '{{ rhel_packages }}'
    when: ansible_distribution == 'RedHat'

  - name: Start all services(Ubuntu/Debian).
    systemd:
      name: '{{ item }}'
      state: started
      enabled: yes
    with_items: '{{ debian_services if ansible_distribution == "Ubuntu" else rhel_services }}'


  - name: Install python's Mysql module.
    pip:
      name: pymysql
      state: present
  
  - import_tasks: firewall.yml
  - import_tasks: mysql_setup.yml
  - import_tasks: apache_config.yml
  - import_tasks: app_setup.yml
  - import_tasks: wordpress.yml