- name: Create root user password.
  mysql_user:
    login_host: 'localhost'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: 'root'
    login_password: ''
    name: root
    password: "{{ root_password }}"
    state: present

- name: Removing all anonymous users.
  mysql_user:
    name: ''
    host: localhost
    state: absent
    login_user: root
    login_password: "{{ root_password }}"

- name: Creating a super user.
  mysql_user:
    user: &mysql_user elartey
    password: '{{ user_password }}'
    priv: '*.*:ALL'
    state: present
    login_user: 'root'
    login_password: "{{ root_password }}"
  notify: Restart mysql

- name: Creating a database for wordpress.
  mysql_db:
    name: '{{ database_name }}'
    state: present
    login_user: *mysql_user
    login_password: '{{ user_password }}'